// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CheckFlowDialogue
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// checkflow11
        /// </summary>
        public void checkflow11()
        {
            #region Variable Declarations
            WinButton uIStartButton = this.UIStartWindow.UIStartButton;
            WinMenuItem uIVisualDialogueMenuItem = this.UIStartmenuWindow.UIItemWindow.UIStartmenuClient.UIVisualDialogueMenuItem;
            WinButton uIOKButton = this.UILogintoVisualDialoguWindow.UIItemWindow.UILogintoVisualDialoguClient.UIOKButton;
            WinWindow uIItemWindow = this.UIVisualDialogueWindow.UIVisualDialogueClient.UIItemWindow;
            WinClient uIExplorerBarClient = this.UIVisualDialogueWindow.UIItemWindow.UIExplorerBarClient;
            WinListItem uIAaQP11SendQuoteConfiListItem = this.UIVisualDialogueWindow.UIItemWindow1.UIItemList.UIAaQP11SendQuoteConfiListItem;
            WinClient uIVisualDialogueClient = this.UIVisualDialogueWindow.UIItemWindow2.UIVisualDialogueClient;
            #endregion

            // Click 'Start' button
            Mouse.Click(uIStartButton, new Point(28, 25));

            // Click 'Visual Dialogue' menu item
            Mouse.Click(uIVisualDialogueMenuItem, new Point(86, 21));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(43, 7));

            // Click window
            Mouse.Click(uIItemWindow, new Point(51, 45));

            // Click 'Explorer Bar' client
            Mouse.Click(uIExplorerBarClient, new Point(59, 136));

            // Double-Click 'Aa- QP 11 - Send Quote Confirmation - Chris' list item
            Mouse.DoubleClick(uIAaQP11SendQuoteConfiListItem, new Point(75, 13));

            // Wait for 10 seconds for user delay between actions; Click 'Visual Dialogue' client
            Playback.Wait(15000);
            Mouse.Click(uIVisualDialogueClient, new Point(1890, 14));
        }
        
        #region Properties
        public UIStartWindow UIStartWindow
        {
            get
            {
                if ((this.mUIStartWindow == null))
                {
                    this.mUIStartWindow = new UIStartWindow();
                }
                return this.mUIStartWindow;
            }
        }
        
        public UIStartmenuWindow UIStartmenuWindow
        {
            get
            {
                if ((this.mUIStartmenuWindow == null))
                {
                    this.mUIStartmenuWindow = new UIStartmenuWindow();
                }
                return this.mUIStartmenuWindow;
            }
        }
        
        public UILogintoVisualDialoguWindow UILogintoVisualDialoguWindow
        {
            get
            {
                if ((this.mUILogintoVisualDialoguWindow == null))
                {
                    this.mUILogintoVisualDialoguWindow = new UILogintoVisualDialoguWindow();
                }
                return this.mUILogintoVisualDialoguWindow;
            }
        }
        
        public UIVisualDialogueWindow UIVisualDialogueWindow
        {
            get
            {
                if ((this.mUIVisualDialogueWindow == null))
                {
                    this.mUIVisualDialogueWindow = new UIVisualDialogueWindow();
                }
                return this.mUIVisualDialogueWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIStartWindow mUIStartWindow;
        
        private UIStartmenuWindow mUIStartmenuWindow;
        
        private UILogintoVisualDialoguWindow mUILogintoVisualDialoguWindow;
        
        private UIVisualDialogueWindow mUIVisualDialogueWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIStartWindow : WinWindow
    {
        
        public UIStartWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Start";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
            this.WindowTitles.Add("Start");
            #endregion
        }
        
        #region Properties
        public WinButton UIStartButton
        {
            get
            {
                if ((this.mUIStartButton == null))
                {
                    this.mUIStartButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIStartButton.SearchProperties[WinButton.PropertyNames.Name] = "Start";
                    this.mUIStartButton.WindowTitles.Add("Start");
                    #endregion
                }
                return this.mUIStartButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIStartButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIStartmenuWindow : WinWindow
    {
        
        public UIStartmenuWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Start menu";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DV2ControlHost";
            this.WindowTitles.Add("Start menu");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "2";
            this.WindowTitles.Add("Start menu");
            #endregion
        }
        
        #region Properties
        public UIStartmenuClient UIStartmenuClient
        {
            get
            {
                if ((this.mUIStartmenuClient == null))
                {
                    this.mUIStartmenuClient = new UIStartmenuClient(this);
                }
                return this.mUIStartmenuClient;
            }
        }
        #endregion
        
        #region Fields
        private UIStartmenuClient mUIStartmenuClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIStartmenuClient : WinClient
    {
        
        public UIStartmenuClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Start menu");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIVisualDialogueMenuItem
        {
            get
            {
                if ((this.mUIVisualDialogueMenuItem == null))
                {
                    this.mUIVisualDialogueMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIVisualDialogueMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Visual Dialogue";
                    this.mUIVisualDialogueMenuItem.WindowTitles.Add("Start menu");
                    #endregion
                }
                return this.mUIVisualDialogueMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIVisualDialogueMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILogintoVisualDialoguWindow : WinWindow
    {
        
        public UILogintoVisualDialoguWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Login to Visual Dialogue";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TfrmVDLogin";
            this.WindowTitles.Add("Login to Visual Dialogue");
            #endregion
        }
        
        #region Properties
        public UIItemWindow1 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow1(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow1 mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TPanel";
            this.WindowTitles.Add("Login to Visual Dialogue");
            #endregion
        }
        
        #region Properties
        public UILogintoVisualDialoguClient UILogintoVisualDialoguClient
        {
            get
            {
                if ((this.mUILogintoVisualDialoguClient == null))
                {
                    this.mUILogintoVisualDialoguClient = new UILogintoVisualDialoguClient(this);
                }
                return this.mUILogintoVisualDialoguClient;
            }
        }
        #endregion
        
        #region Fields
        private UILogintoVisualDialoguClient mUILogintoVisualDialoguClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILogintoVisualDialoguClient : WinClient
    {
        
        public UILogintoVisualDialoguClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Login to Visual Dialogue");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("Login to Visual Dialogue");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIVisualDialogueWindow : WinWindow
    {
        
        public UIVisualDialogueWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Visual Dialogue";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TfrmVDMain";
            this.WindowTitles.Add("Visual Dialogue");
            #endregion
        }
        
        #region Properties
        public UIVisualDialogueClient UIVisualDialogueClient
        {
            get
            {
                if ((this.mUIVisualDialogueClient == null))
                {
                    this.mUIVisualDialogueClient = new UIVisualDialogueClient(this);
                }
                return this.mUIVisualDialogueClient;
            }
        }
        
        public UIItemWindow2 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow2(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItemWindow11 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow11(this);
                }
                return this.mUIItemWindow1;
            }
        }
        
        public UIItemWindow21 UIItemWindow2
        {
            get
            {
                if ((this.mUIItemWindow2 == null))
                {
                    this.mUIItemWindow2 = new UIItemWindow21(this);
                }
                return this.mUIItemWindow2;
            }
        }
        #endregion
        
        #region Fields
        private UIVisualDialogueClient mUIVisualDialogueClient;
        
        private UIItemWindow2 mUIItemWindow;
        
        private UIItemWindow11 mUIItemWindow1;
        
        private UIItemWindow21 mUIItemWindow2;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIVisualDialogueClient : WinClient
    {
        
        public UIVisualDialogueClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Visual Dialogue";
            this.WindowTitles.Add("Visual Dialogue");
            #endregion
        }
        
        #region Properties
        public WinWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIItemWindow.SearchProperties[WinWindow.PropertyNames.ClassName] = "TdxRibbonBackstageView";
                    this.mUIItemWindow.WindowTitles.Add("Visual Dialogue");
                    #endregion
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow2 : WinWindow
    {
        
        public UIItemWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TdxNavBar";
            this.WindowTitles.Add("Visual Dialogue");
            #endregion
        }
        
        #region Properties
        public WinClient UIExplorerBarClient
        {
            get
            {
                if ((this.mUIExplorerBarClient == null))
                {
                    this.mUIExplorerBarClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIExplorerBarClient.WindowTitles.Add("Visual Dialogue");
                    #endregion
                }
                return this.mUIExplorerBarClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIExplorerBarClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow11 : WinWindow
    {
        
        public UIItemWindow11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TcxCustomInnerListView";
            this.WindowTitles.Add("Visual Dialogue");
            #endregion
        }
        
        #region Properties
        public UIItemList UIItemList
        {
            get
            {
                if ((this.mUIItemList == null))
                {
                    this.mUIItemList = new UIItemList(this);
                }
                return this.mUIItemList;
            }
        }
        #endregion
        
        #region Fields
        private UIItemList mUIItemList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemList : WinList
    {
        
        public UIItemList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Visual Dialogue");
            #endregion
        }
        
        #region Properties
        public WinListItem UIAaQP11SendQuoteConfiListItem
        {
            get
            {
                if ((this.mUIAaQP11SendQuoteConfiListItem == null))
                {
                    this.mUIAaQP11SendQuoteConfiListItem = new WinListItem(this);
                    #region Search Criteria
                    this.mUIAaQP11SendQuoteConfiListItem.SearchProperties[WinListItem.PropertyNames.Name] = "Aa- QP 11 - Send Quote Confirmation - Chris";
                    this.mUIAaQP11SendQuoteConfiListItem.WindowTitles.Add("Visual Dialogue");
                    #endregion
                }
                return this.mUIAaQP11SendQuoteConfiListItem;
            }
        }
        #endregion
        
        #region Fields
        private WinListItem mUIAaQP11SendQuoteConfiListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow21 : WinWindow
    {
        
        public UIItemWindow21(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TdxRibbon";
            this.WindowTitles.Add("Visual Dialogue");
            #endregion
        }
        
        #region Properties
        public WinClient UIVisualDialogueClient
        {
            get
            {
                if ((this.mUIVisualDialogueClient == null))
                {
                    this.mUIVisualDialogueClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIVisualDialogueClient.WindowTitles.Add("Visual Dialogue");
                    #endregion
                }
                return this.mUIVisualDialogueClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIVisualDialogueClient;
        #endregion
    }
}
