// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject4
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Assert1 - Use 'Assert1ExpectedValues' to pass parameters into this method.
        /// </summary>
        public void Assert1()
        {
            #region Variable Declarations
            HtmlCell uIQP102QuoteConfirmatiCell = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument2.UIOne2many__ctl4_ifrmOFrame1.UIOne2ManyDocument.UI_ctl0_gridOne2ManyTable.UIQP102QuoteConfirmatiCell;
            HtmlCell uIAaQP11SendQuoteConfiCell = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument2.UIOne2many__ctl4_ifrmOFrame.UIOne2ManyDocument.UI_ctl0_gridOne2ManyTable.UIAaQP11SendQuoteConfiCell;
            HtmlDiv uIHiAaaaaWevesavedyourPane = this.UIEmailMessageInternetWindow.UIEmailMessageDocument.UI_ctl0_MessageContentFrame.UINewsletterDocument.UIMainSection_item_0Table.UIHiAaaaaWevesavedyourPane;
            HtmlSpan uICoveaInsuranceplcisrPane = this.UIEmailMessageInternetWindow.UIEmailMessageDocument.UI_ctl0_MessageContentFrame.UINewsletterDocument.UICoveaInsuranceplcisrPane;
            #endregion

            // Verify that the 'InnerText' property of 'QP - 102 Quote Confirmation' cell equals 'QP - 102 Quote Confirmation'
            Assert.AreEqual(this.Assert1ExpectedValues.UIQP102QuoteConfirmatiCellInnerText, uIQP102QuoteConfirmatiCell.InnerText);

            // Verify that the 'InnerText' property of 'Aa- QP 11 - Send Quote Confirmation - Ch' cell equals 'Aa- QP 11 - Send Quote Confirmation - Chris'
            Assert.AreEqual(this.Assert1ExpectedValues.UIAaQP11SendQuoteConfiCellInnerText, uIAaQP11SendQuoteConfiCell.InnerText);

            // Verify that the 'TagName' property of 'Hi Aaaaa, We've saved your quote with' pane equals 'DIV'
            Assert.AreEqual(this.Assert1ExpectedValues.UIHiAaaaaWevesavedyourPaneTagName, uIHiAaaaaWevesavedyourPane.TagName);

            // Verify that the 'TagName' property of 'Covea Insurance plc is registered in Eng' pane equals 'SPAN'
            Assert.AreEqual(this.Assert1ExpectedValues.UICoveaInsuranceplcisrPaneTagName, uICoveaInsuranceplcisrPane.TagName);
        }
        
        /// <summary>
        /// openemail
        /// </summary>
        public void openemail()
        {
            #region Variable Declarations
            HtmlDiv uIMainSecondaryPane1 = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument2.UIMainSecondaryPane.UIMainSecondaryPane1;
            HtmlDiv uICustomerInfo__ctl4_fPane = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument2.UICustomerInfo__ctl4_fPane;
            HtmlCell uIItemCell = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument2.UICustomerInfo__ctl4_mTable.UIItemCell;
            HtmlCell uIQP102QuoteConfirmatiCell = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument2.UIOne2many__ctl4_ifrmOFrame1.UIOne2ManyDocument.UI_ctl0_gridOne2ManyTable.UIQP102QuoteConfirmatiCell;
            HtmlDiv uIOne2many_bodyPanelPane = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument2.UIOne2many_bodyPanelPane;
            HtmlCell uIItemCell1 = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument2.UIOne2many__ctl4_one2MTable.UIItemCell1;
            BrowserWindow uIEmailMessageInternetWindow = this.UIEmailMessageInternetWindow;
            #endregion

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'Main Secondary' pane at (1, 1)
            Mouse.Hover(uIMainSecondaryPane1, new Point(1, 1));

            // Mouse hover 'CustomerInfo__ctl4_fldpanelTab1Right' pane at (1, 1)
            Mouse.Hover(uICustomerInfo__ctl4_fPane, new Point(1, 1));

            // Mouse hover  cell at (1, 1)
            Mouse.Hover(uIItemCell, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Double-Click 'QP - 102 Quote Confirmation' cell
            Mouse.DoubleClick(uIQP102QuoteConfirmatiCell, new Point(122, 9));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'one2many_bodyPanel' pane at (1, 1)
            Mouse.Hover(uIOne2many_bodyPanelPane, new Point(1, 1));

            // Mouse hover  cell at (1, 1)
            Mouse.Hover(uIItemCell1, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Perform Close on Browser Window
            uIEmailMessageInternetWindow.Close();
        }
        
        /// <summary>
        /// ValidateDialogue - Use 'ValidateDialogueParams' to pass parameters into this method.
        /// </summary>
        public void ValidateDialogue()
        {
            #region Variable Declarations
            HtmlEdit uIIDEdit = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument.UIIDEdit;
            HtmlCell uIS218267002FVCell = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument.UIDGTable.UIS218267002FVCell;
            HtmlSpan uIClaims_CustomerLevelPane = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument2.UIClaims_CustomerLevelPane;
            HtmlSpan uIDialogsPane1 = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument2.UIDialogsPane.UIDialogsPane1;
            HtmlSpan uIDialogsPane = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument2.UIDialogsPane;
            HtmlCell uIAaQP11SendQuoteConfiCell = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument2.UIOne2many__ctl4_ifrmOFrame.UIOne2ManyDocument.UI_ctl0_gridOne2ManyTable.UIAaQP11SendQuoteConfiCell;
            HtmlSpan uIMessagesPane = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument2.UIMessagesPane;
            HtmlSpan uIMessagesPane1 = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument2.UIMessagesPane.UIMessagesPane1;
            HtmlCell uIQP102QuoteConfirmatiCell = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument2.UIOne2many__ctl4_ifrmOFrame1.UIOne2ManyDocument.UI_ctl0_gridOne2ManyTable.UIQP102QuoteConfirmatiCell;
            HtmlCell uIItemCell = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument2.UIOne2many__ctl4_one2MTable.UIItemCell;
            #endregion

            // Go to web page 'http://stt-pb-pdi-001.test.directpi.co.uk/MhCustomerView/WebPages/Search.aspx?DomainId=1025' using new browser instance
            this.UICoveaHomeInternetExpWindow.LaunchUrl(new System.Uri(this.ValidateDialogueParams.UICoveaHomeInternetExpWindowUrl));

            Keyboard.SendKeys(uIIDEdit, Direct.Properties.Resources.QuoteID1);

            // Type '{Enter}' in 'ID' text box
            Keyboard.SendKeys(uIIDEdit, this.ValidateDialogueParams.UIIDEditSendKeys, ModifierKeys.None);

            // Click 'S2/18267/002FV' cell
            Mouse.Click(uIS218267002FVCell, new Point(60, 12));

            // Double-Click 'S2/18267/002FV' cell
            Mouse.DoubleClick(uIS218267002FVCell, new Point(51, 8));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'Claims_Customer Level' pane at (1, 1)
            Mouse.Hover(uIClaims_CustomerLevelPane, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Dialogs' pane
            Mouse.Click(uIDialogsPane1, new Point(17, 9));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'Dialogs' pane at (1, 1)
            Mouse.Hover(uIDialogsPane, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Aa- QP 11 - Send Quote Confirmation - Ch' cell
            Mouse.Click(uIAaQP11SendQuoteConfiCell, new Point(215, 10));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'Messages' pane at (1, 1)
            Mouse.Hover(uIMessagesPane, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Messages' pane
            Mouse.Click(uIMessagesPane1, new Point(28, 8));

            // Click 'QP - 102 Quote Confirmation' cell
            Mouse.Click(uIQP102QuoteConfirmatiCell, new Point(132, 9));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover  cell at (1, 1)
            Mouse.Hover(uIItemCell, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;
        }
        
        #region Properties
        public virtual Assert1ExpectedValues Assert1ExpectedValues
        {
            get
            {
                if ((this.mAssert1ExpectedValues == null))
                {
                    this.mAssert1ExpectedValues = new Assert1ExpectedValues();
                }
                return this.mAssert1ExpectedValues;
            }
        }
        
        public virtual ValidateDialogueParams ValidateDialogueParams
        {
            get
            {
                if ((this.mValidateDialogueParams == null))
                {
                    this.mValidateDialogueParams = new ValidateDialogueParams();
                }
                return this.mValidateDialogueParams;
            }
        }
        
        public UICoveaHomeInternetExpWindow UICoveaHomeInternetExpWindow
        {
            get
            {
                if ((this.mUICoveaHomeInternetExpWindow == null))
                {
                    this.mUICoveaHomeInternetExpWindow = new UICoveaHomeInternetExpWindow();
                }
                return this.mUICoveaHomeInternetExpWindow;
            }
        }
        
        public UIEmailMessageInternetWindow UIEmailMessageInternetWindow
        {
            get
            {
                if ((this.mUIEmailMessageInternetWindow == null))
                {
                    this.mUIEmailMessageInternetWindow = new UIEmailMessageInternetWindow();
                }
                return this.mUIEmailMessageInternetWindow;
            }
        }
        #endregion
        
        #region Fields
        private Assert1ExpectedValues mAssert1ExpectedValues;
        
        private ValidateDialogueParams mValidateDialogueParams;
        
        private UICoveaHomeInternetExpWindow mUICoveaHomeInternetExpWindow;
        
        private UIEmailMessageInternetWindow mUIEmailMessageInternetWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Assert1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class Assert1ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'QP - 102 Quote Confirmation' cell equals 'QP - 102 Quote Confirmation'
        /// </summary>
        public string UIQP102QuoteConfirmatiCellInnerText = "QP - 102 Quote Confirmation";
        
        /// <summary>
        /// Verify that the 'InnerText' property of 'Aa- QP 11 - Send Quote Confirmation - Ch' cell equals 'Aa- QP 11 - Send Quote Confirmation - Chris'
        /// </summary>
        public string UIAaQP11SendQuoteConfiCellInnerText = "Aa- QP 11 - Send Quote Confirmation - Chris";
        
        /// <summary>
        /// Verify that the 'TagName' property of 'Hi Aaaaa, We've saved your quote with' pane equals 'DIV'
        /// </summary>
        public string UIHiAaaaaWevesavedyourPaneTagName = "DIV";
        
        /// <summary>
        /// Verify that the 'TagName' property of 'Covea Insurance plc is registered in Eng' pane equals 'SPAN'
        /// </summary>
        public string UICoveaInsuranceplcisrPaneTagName = "SPAN";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ValidateDialogue'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class ValidateDialogueParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://stt-pb-pdi-001.test.directpi.co.uk/MhCustomerView/WebPages/Search.aspx?DomainId=1025' using new browser instance
        /// </summary>
        public string UICoveaHomeInternetExpWindowUrl = "http://stt-pb-pdi-001.test.directpi.co.uk/MhCustomerView/WebPages/Search.aspx?Dom" +
            "ainId=1025";
        
        /// <summary>
        /// Type '{Enter}' in 'ID' text box
        /// </summary>
        public string UIIDEditSendKeys = "{Enter}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICoveaHomeInternetExpWindow : BrowserWindow
    {
        
        public UICoveaHomeInternetExpWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "CoveaHome";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("CoveaHome");
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UICustomerViewDocument UICustomerViewDocument
        {
            get
            {
                if ((this.mUICustomerViewDocument == null))
                {
                    this.mUICustomerViewDocument = new UICustomerViewDocument(this);
                }
                return this.mUICustomerViewDocument;
            }
        }
        
        public UICustomerViewDocument2 UICustomerViewDocument2
        {
            get
            {
                if ((this.mUICustomerViewDocument2 == null))
                {
                    this.mUICustomerViewDocument2 = new UICustomerViewDocument2(this);
                }
                return this.mUICustomerViewDocument2;
            }
        }
        #endregion
        
        #region Fields
        private UICustomerViewDocument mUICustomerViewDocument;
        
        private UICustomerViewDocument2 mUICustomerViewDocument2;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICustomerViewDocument : HtmlDocument
    {
        
        public UICustomerViewDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "Body";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Customer View";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/MhCustomerView/WebPages/Search.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://stt-pb-pdi-001.test.directpi.co.uk/MhCustomerView/WebPages/Search.aspx?Dom" +
                "ainId=1025";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIIDEdit
        {
            get
            {
                if ((this.mUIIDEdit == null))
                {
                    this.mUIIDEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIIDEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "SearchPanel_Normal_QuotePolicy__QE_ID";
                    this.mUIIDEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "SearchPanel:Normal:QuotePolicy__QE_ID";
                    this.mUIIDEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIIDEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIIDEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIIDEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "input";
                    this.mUIIDEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "onfocus=\"javascript: document.getElement";
                    this.mUIIDEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "15";
                    this.mUIIDEdit.WindowTitles.Add("Customer View");
                    #endregion
                }
                return this.mUIIDEdit;
            }
        }
        
        public UIDGTable UIDGTable
        {
            get
            {
                if ((this.mUIDGTable == null))
                {
                    this.mUIDGTable = new UIDGTable(this);
                }
                return this.mUIDGTable;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIIDEdit;
        
        private UIDGTable mUIDGTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDGTable : HtmlTable
    {
        
        public UIDGTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = "Dg";
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "mh_customer_idmh_contextmh_participant_i";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "id=Dg class=grid onselectstart=\"return false\" style=\"WIDTH: 100%; BORDER-COLLAPSE" +
                ": collapse\" cellSpacing=0 rules=all border=1";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "2";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "97";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "grid";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "567";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public HtmlCell UIS218267002FVCell
        {
            get
            {
                if ((this.mUIS218267002FVCell == null))
                {
                    this.mUIS218267002FVCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIS218267002FVCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIS218267002FVCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIS218267002FVCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIS218267002FVCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "S2/18267/002FV";
                    this.mUIS218267002FVCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "noWrap";
                    this.mUIS218267002FVCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "1";
                    this.mUIS218267002FVCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "5";
                    this.mUIS218267002FVCell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUIS218267002FVCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "1295";
                    this.mUIS218267002FVCell.WindowTitles.Add("Customer View");
                    #endregion
                }
                return this.mUIS218267002FVCell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUIS218267002FVCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICustomerViewDocument2 : HtmlDocument
    {
        
        public UICustomerViewDocument2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "Body";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Customer View";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/MhCustomerView/WebPages/Customer.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://stt-pb-pdi-001.test.directpi.co.uk/MhCustomerView/WebPages/Customer.aspx?D" +
                "omainId=1025&CustomerId=101607";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public HtmlSpan UIClaims_CustomerLevelPane
        {
            get
            {
                if ((this.mUIClaims_CustomerLevelPane == null))
                {
                    this.mUIClaims_CustomerLevelPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIClaims_CustomerLevelPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "one2many__ctl4_tabStrip_tab_2";
                    this.mUIClaims_CustomerLevelPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIClaims_CustomerLevelPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Claims_Customer Level";
                    this.mUIClaims_CustomerLevelPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIClaims_CustomerLevelPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "TabItem";
                    this.mUIClaims_CustomerLevelPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = @"onclick=""javascript: one2many__ctl4_tabStrip_Click(one2many__ctl4_tabStrip_tab_2,'one2many__ctl4_TabStrip_',2,14,'TabItem','TabItemSelected');"" onmouseover=""javascript: this.style.cursor = 'hand'"" id=one2many__ctl4_tabStrip_tab_2 class=TabItem style=""CURSOR: hand; HEIGHT: 21px; DISPLAY: inline-block""";
                    this.mUIClaims_CustomerLevelPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "638";
                    this.mUIClaims_CustomerLevelPane.WindowTitles.Add("Customer View");
                    #endregion
                }
                return this.mUIClaims_CustomerLevelPane;
            }
        }
        
        public UIDialogsPane UIDialogsPane
        {
            get
            {
                if ((this.mUIDialogsPane == null))
                {
                    this.mUIDialogsPane = new UIDialogsPane(this);
                }
                return this.mUIDialogsPane;
            }
        }
        
        public UIOne2many__ctl4_ifrmOFrame UIOne2many__ctl4_ifrmOFrame
        {
            get
            {
                if ((this.mUIOne2many__ctl4_ifrmOFrame == null))
                {
                    this.mUIOne2many__ctl4_ifrmOFrame = new UIOne2many__ctl4_ifrmOFrame(this);
                }
                return this.mUIOne2many__ctl4_ifrmOFrame;
            }
        }
        
        public UIMessagesPane UIMessagesPane
        {
            get
            {
                if ((this.mUIMessagesPane == null))
                {
                    this.mUIMessagesPane = new UIMessagesPane(this);
                }
                return this.mUIMessagesPane;
            }
        }
        
        public UIOne2many__ctl4_ifrmOFrame1 UIOne2many__ctl4_ifrmOFrame1
        {
            get
            {
                if ((this.mUIOne2many__ctl4_ifrmOFrame1 == null))
                {
                    this.mUIOne2many__ctl4_ifrmOFrame1 = new UIOne2many__ctl4_ifrmOFrame1(this);
                }
                return this.mUIOne2many__ctl4_ifrmOFrame1;
            }
        }
        
        public UIOne2many__ctl4_one2MTable UIOne2many__ctl4_one2MTable
        {
            get
            {
                if ((this.mUIOne2many__ctl4_one2MTable == null))
                {
                    this.mUIOne2many__ctl4_one2MTable = new UIOne2many__ctl4_one2MTable(this);
                }
                return this.mUIOne2many__ctl4_one2MTable;
            }
        }
        
        public UIDriversPane UIDriversPane
        {
            get
            {
                if ((this.mUIDriversPane == null))
                {
                    this.mUIDriversPane = new UIDriversPane(this);
                }
                return this.mUIDriversPane;
            }
        }
        
        public UIMainSecondaryPane UIMainSecondaryPane
        {
            get
            {
                if ((this.mUIMainSecondaryPane == null))
                {
                    this.mUIMainSecondaryPane = new UIMainSecondaryPane(this);
                }
                return this.mUIMainSecondaryPane;
            }
        }
        
        public HtmlDiv UICustomerInfo__ctl4_fPane
        {
            get
            {
                if ((this.mUICustomerInfo__ctl4_fPane == null))
                {
                    this.mUICustomerInfo__ctl4_fPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUICustomerInfo__ctl4_fPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "CustomerInfo__ctl4_fldpanelTab1Right";
                    this.mUICustomerInfo__ctl4_fPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUICustomerInfo__ctl4_fPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Quote Policy\r\n\r\nQuote Policy_URN101607\r\n";
                    this.mUICustomerInfo__ctl4_fPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUICustomerInfo__ctl4_fPane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUICustomerInfo__ctl4_fPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = @"id=CustomerInfo__ctl4_fldpanelTab1Right style=""SCROLLBAR-HIGHLIGHT-COLOR: lightsteelblue; HEIGHT: 100%; WIDTH: 100%; SCROLLBAR-TRACK-COLOR: lightsteelblue; OVERFLOW-Y: auto; SCROLLBAR-FACE-COLOR: #639ace; SCROLLBAR-ARROW-COLOR: #d1d1d1; SCROLLBAR-SHADOW-COLOR: lightsteelblue""";
                    this.mUICustomerInfo__ctl4_fPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "18";
                    this.mUICustomerInfo__ctl4_fPane.WindowTitles.Add("Customer View");
                    #endregion
                }
                return this.mUICustomerInfo__ctl4_fPane;
            }
        }
        
        public UICustomerInfo__ctl4_mTable UICustomerInfo__ctl4_mTable
        {
            get
            {
                if ((this.mUICustomerInfo__ctl4_mTable == null))
                {
                    this.mUICustomerInfo__ctl4_mTable = new UICustomerInfo__ctl4_mTable(this);
                }
                return this.mUICustomerInfo__ctl4_mTable;
            }
        }
        
        public HtmlDiv UIOne2many_bodyPanelPane
        {
            get
            {
                if ((this.mUIOne2many_bodyPanelPane == null))
                {
                    this.mUIOne2many_bodyPanelPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIOne2many_bodyPanelPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "one2many_bodyPanel";
                    this.mUIOne2many_bodyPanelPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIOne2many_bodyPanelPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Drivers\r\nClaims\r\nClaims_Customer Level\r\n";
                    this.mUIOne2many_bodyPanelPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIOne2many_bodyPanelPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "BodyCss2";
                    this.mUIOne2many_bodyPanelPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=one2many_bodyPanel class=BodyCss2 style=\"HEIGHT: 100%; WIDTH: 100%\"";
                    this.mUIOne2many_bodyPanelPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "27";
                    this.mUIOne2many_bodyPanelPane.WindowTitles.Add("Customer View");
                    #endregion
                }
                return this.mUIOne2many_bodyPanelPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlSpan mUIClaims_CustomerLevelPane;
        
        private UIDialogsPane mUIDialogsPane;
        
        private UIOne2many__ctl4_ifrmOFrame mUIOne2many__ctl4_ifrmOFrame;
        
        private UIMessagesPane mUIMessagesPane;
        
        private UIOne2many__ctl4_ifrmOFrame1 mUIOne2many__ctl4_ifrmOFrame1;
        
        private UIOne2many__ctl4_one2MTable mUIOne2many__ctl4_one2MTable;
        
        private UIDriversPane mUIDriversPane;
        
        private UIMainSecondaryPane mUIMainSecondaryPane;
        
        private HtmlDiv mUICustomerInfo__ctl4_fPane;
        
        private UICustomerInfo__ctl4_mTable mUICustomerInfo__ctl4_mTable;
        
        private HtmlDiv mUIOne2many_bodyPanelPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDialogsPane : HtmlSpan
    {
        
        public UIDialogsPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "one2many__ctl4_tabStrip_tab_10";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Dialogs";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "TabItem";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = @"onclick=""javascript: one2many__ctl4_tabStrip_Click(one2many__ctl4_tabStrip_tab_10,'one2many__ctl4_TabStrip_',10,14,'TabItem','TabItemSelected');"" onmouseover=""javascript: this.style.cursor = 'hand'"" id=one2many__ctl4_tabStrip_tab_10 class=TabItem style=""HEIGHT: 21px; DISPLAY: inline-block""";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "654";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public HtmlSpan UIDialogsPane1
        {
            get
            {
                if ((this.mUIDialogsPane1 == null))
                {
                    this.mUIDialogsPane1 = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIDialogsPane1.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIDialogsPane1.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIDialogsPane1.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Dialogs";
                    this.mUIDialogsPane1.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIDialogsPane1.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIDialogsPane1.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = null;
                    this.mUIDialogsPane1.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "655";
                    this.mUIDialogsPane1.WindowTitles.Add("Customer View");
                    #endregion
                }
                return this.mUIDialogsPane1;
            }
        }
        #endregion
        
        #region Fields
        private HtmlSpan mUIDialogsPane1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIOne2many__ctl4_ifrmOFrame : HtmlIFrame
    {
        
        public UIOne2many__ctl4_ifrmOFrame(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlFrame.PropertyNames.Id] = "one2many__ctl4_ifrmOne2Many10";
            this.SearchProperties[HtmlFrame.PropertyNames.Name] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.AbsolutePath] = "/MHCustomerView/WebPages/One2ManyGroup.aspx";
            this.FilterProperties[HtmlFrame.PropertyNames.PageUrl] = "/MHCustomerView/WebPages/One2ManyGroup.aspx?DGN=Dialogs&CustomerId=101607&CustDom" +
                "ainId=1025";
            this.FilterProperties[HtmlFrame.PropertyNames.Title] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.Class] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "id=one2many__ctl4_ifrmOne2Many10 style=\"";
            this.FilterProperties[HtmlFrame.PropertyNames.TagInstance] = "11";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public UIOne2ManyDocument UIOne2ManyDocument
        {
            get
            {
                if ((this.mUIOne2ManyDocument == null))
                {
                    this.mUIOne2ManyDocument = new UIOne2ManyDocument(this);
                }
                return this.mUIOne2ManyDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIOne2ManyDocument mUIOne2ManyDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIOne2ManyDocument : HtmlDocument
    {
        
        public UIOne2ManyDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "One2Many";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/MHCustomerView/WebPages/One2ManyGroup.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://stt-pb-pdi-001.test.directpi.co.uk/MHCustomerView/WebPages/One2ManyGroup.a" +
                "spx?DGN=Dialogs&CustomerId=101607&CustDomainId=1025";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public UI_ctl0_gridOne2ManyTable UI_ctl0_gridOne2ManyTable
        {
            get
            {
                if ((this.mUI_ctl0_gridOne2ManyTable == null))
                {
                    this.mUI_ctl0_gridOne2ManyTable = new UI_ctl0_gridOne2ManyTable(this);
                }
                return this.mUI_ctl0_gridOne2ManyTable;
            }
        }
        #endregion
        
        #region Fields
        private UI_ctl0_gridOne2ManyTable mUI_ctl0_gridOne2ManyTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UI_ctl0_gridOne2ManyTable : HtmlTable
    {
        
        public UI_ctl0_gridOne2ManyTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = "_ctl0_gridOne2Many";
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "dp_idDialog NameGroup NameContextEntered";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "id=_ctl0_gridOne2Many style=\"WIDTH: 100%; BORDER-COLLAPSE: collapse\" cellSpacing=" +
                "0 rules=all border=1";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "2";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "6";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = null;
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "2";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public HtmlCell UIAaQP11SendQuoteConfiCell
        {
            get
            {
                if ((this.mUIAaQP11SendQuoteConfiCell == null))
                {
                    this.mUIAaQP11SendQuoteConfiCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIAaQP11SendQuoteConfiCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIAaQP11SendQuoteConfiCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIAaQP11SendQuoteConfiCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIAaQP11SendQuoteConfiCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "Aa- QP 11 - Send Quote Confirmation - Ch";
                    this.mUIAaQP11SendQuoteConfiCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "noWrap Unselectable=\"On\"";
                    this.mUIAaQP11SendQuoteConfiCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "1";
                    this.mUIAaQP11SendQuoteConfiCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "1";
                    this.mUIAaQP11SendQuoteConfiCell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUIAaQP11SendQuoteConfiCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "9";
                    this.mUIAaQP11SendQuoteConfiCell.WindowTitles.Add("Customer View");
                    #endregion
                }
                return this.mUIAaQP11SendQuoteConfiCell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUIAaQP11SendQuoteConfiCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMessagesPane : HtmlSpan
    {
        
        public UIMessagesPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "one2many__ctl4_tabStrip_tab_9";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Messages";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "TabItem";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = @"onclick=""javascript: one2many__ctl4_tabStrip_Click(one2many__ctl4_tabStrip_tab_9,'one2many__ctl4_TabStrip_',9,14,'TabItem','TabItemSelected');"" onmouseover=""javascript: this.style.cursor = 'hand'"" id=one2many__ctl4_tabStrip_tab_9 class=TabItem style=""HEIGHT: 21px; DISPLAY: inline-block""";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "652";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public HtmlSpan UIMessagesPane1
        {
            get
            {
                if ((this.mUIMessagesPane1 == null))
                {
                    this.mUIMessagesPane1 = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIMessagesPane1.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIMessagesPane1.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIMessagesPane1.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Messages";
                    this.mUIMessagesPane1.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIMessagesPane1.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIMessagesPane1.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = null;
                    this.mUIMessagesPane1.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "653";
                    this.mUIMessagesPane1.WindowTitles.Add("Customer View");
                    #endregion
                }
                return this.mUIMessagesPane1;
            }
        }
        #endregion
        
        #region Fields
        private HtmlSpan mUIMessagesPane1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIOne2many__ctl4_ifrmOFrame1 : HtmlIFrame
    {
        
        public UIOne2many__ctl4_ifrmOFrame1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlFrame.PropertyNames.Id] = "one2many__ctl4_ifrmOne2Many9";
            this.SearchProperties[HtmlFrame.PropertyNames.Name] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.AbsolutePath] = "/MHCustomerView/WebPages/One2ManyGroup.aspx";
            this.FilterProperties[HtmlFrame.PropertyNames.PageUrl] = "/MHCustomerView/WebPages/One2ManyGroup.aspx?DGN=Messages&CustomerId=101607&CustDo" +
                "mainId=1025";
            this.FilterProperties[HtmlFrame.PropertyNames.Title] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.Class] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "id=one2many__ctl4_ifrmOne2Many9 style=\"H";
            this.FilterProperties[HtmlFrame.PropertyNames.TagInstance] = "10";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public UIOne2ManyDocument1 UIOne2ManyDocument
        {
            get
            {
                if ((this.mUIOne2ManyDocument == null))
                {
                    this.mUIOne2ManyDocument = new UIOne2ManyDocument1(this);
                }
                return this.mUIOne2ManyDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIOne2ManyDocument1 mUIOne2ManyDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIOne2ManyDocument1 : HtmlDocument
    {
        
        public UIOne2ManyDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "One2Many";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/MHCustomerView/WebPages/One2ManyGroup.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://stt-pb-pdi-001.test.directpi.co.uk/MHCustomerView/WebPages/One2ManyGroup.a" +
                "spx?DGN=Messages&CustomerId=101607&CustDomainId=1025";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public UI_ctl0_gridOne2ManyTable1 UI_ctl0_gridOne2ManyTable
        {
            get
            {
                if ((this.mUI_ctl0_gridOne2ManyTable == null))
                {
                    this.mUI_ctl0_gridOne2ManyTable = new UI_ctl0_gridOne2ManyTable1(this);
                }
                return this.mUI_ctl0_gridOne2ManyTable;
            }
        }
        #endregion
        
        #region Fields
        private UI_ctl0_gridOne2ManyTable1 mUI_ctl0_gridOne2ManyTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UI_ctl0_gridOne2ManyTable1 : HtmlTable
    {
        
        public UI_ctl0_gridOne2ManyTable1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = "_ctl0_gridOne2Many";
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "ml_idcm_idMessage NameTypeContextCreated";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "id=_ctl0_gridOne2Many style=\"WIDTH: 100%; BORDER-COLLAPSE: collapse\" cellSpacing=" +
                "0 rules=all border=1";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "2";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "11";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = null;
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "2";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public HtmlCell UIQP102QuoteConfirmatiCell
        {
            get
            {
                if ((this.mUIQP102QuoteConfirmatiCell == null))
                {
                    this.mUIQP102QuoteConfirmatiCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIQP102QuoteConfirmatiCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIQP102QuoteConfirmatiCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIQP102QuoteConfirmatiCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIQP102QuoteConfirmatiCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "QP - 102 Quote Confirmation";
                    this.mUIQP102QuoteConfirmatiCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "noWrap Unselectable=\"On\"";
                    this.mUIQP102QuoteConfirmatiCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "1";
                    this.mUIQP102QuoteConfirmatiCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "2";
                    this.mUIQP102QuoteConfirmatiCell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUIQP102QuoteConfirmatiCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "15";
                    this.mUIQP102QuoteConfirmatiCell.WindowTitles.Add("Customer View");
                    #endregion
                }
                return this.mUIQP102QuoteConfirmatiCell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUIQP102QuoteConfirmatiCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIOne2many__ctl4_one2MTable : HtmlTable
    {
        
        public UIOne2many__ctl4_one2MTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = "one2many__ctl4_one2ManyTable";
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Drivers\r\nClaims\r\nClaims_Customer Level\r\n";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "id=one2many__ctl4_one2ManyTable style=\"HEIGHT: 100%; WIDTH: 100%\" cellSpacing=0 c" +
                "ellPadding=0";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "4";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "1";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = null;
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "356";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public HtmlCell UIItemCell
        {
            get
            {
                if ((this.mUIItemCell == null))
                {
                    this.mUIItemCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = null;
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = null;
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "2";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "1077";
                    this.mUIItemCell.WindowTitles.Add("Customer View");
                    #endregion
                }
                return this.mUIItemCell;
            }
        }
        
        public HtmlCell UIItemCell1
        {
            get
            {
                if ((this.mUIItemCell1 == null))
                {
                    this.mUIItemCell1 = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIItemCell1.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIItemCell1.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIItemCell1.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIItemCell1.SearchProperties[HtmlCell.PropertyNames.InnerText] = null;
                    this.mUIItemCell1.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "style=\"HEIGHT: 0px\" align=right";
                    this.mUIItemCell1.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "0";
                    this.mUIItemCell1.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
                    this.mUIItemCell1.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUIItemCell1.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "1033";
                    this.mUIItemCell1.WindowTitles.Add("Customer View");
                    #endregion
                }
                return this.mUIItemCell1;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUIItemCell;
        
        private HtmlCell mUIItemCell1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDriversPane : HtmlSpan
    {
        
        public UIDriversPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "one2many__ctl4_tabStrip_tab_0";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Drivers";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "TabItem";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = @"onclick=""javascript: one2many__ctl4_tabStrip_Click(one2many__ctl4_tabStrip_tab_0,'one2many__ctl4_TabStrip_',0,14,'TabItem','TabItemSelected');"" onmouseover=""javascript: this.style.cursor = 'hand'"" id=one2many__ctl4_tabStrip_tab_0 class=TabItem style=""HEIGHT: 21px; DISPLAY: inline-block""";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "634";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public HtmlSpan UIDriversPane1
        {
            get
            {
                if ((this.mUIDriversPane1 == null))
                {
                    this.mUIDriversPane1 = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIDriversPane1.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIDriversPane1.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIDriversPane1.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Drivers";
                    this.mUIDriversPane1.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIDriversPane1.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIDriversPane1.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = null;
                    this.mUIDriversPane1.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "635";
                    this.mUIDriversPane1.WindowTitles.Add("Customer View");
                    #endregion
                }
                return this.mUIDriversPane1;
            }
        }
        #endregion
        
        #region Fields
        private HtmlSpan mUIDriversPane1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMainSecondaryPane : HtmlDiv
    {
        
        public UIMainSecondaryPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "CustomerInfo__ctl4_infoTabs";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Main\r\nSecondary";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=CustomerInfo__ctl4_infoTabs style=\"HEIGHT: 21px; WIDTH: 100%\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "13";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIMainSecondaryPane1
        {
            get
            {
                if ((this.mUIMainSecondaryPane1 == null))
                {
                    this.mUIMainSecondaryPane1 = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIMainSecondaryPane1.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIMainSecondaryPane1.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIMainSecondaryPane1.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Main\r\nSecondary";
                    this.mUIMainSecondaryPane1.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIMainSecondaryPane1.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIMainSecondaryPane1.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "style=\"WIDTH: 100%\"";
                    this.mUIMainSecondaryPane1.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "14";
                    this.mUIMainSecondaryPane1.WindowTitles.Add("Customer View");
                    #endregion
                }
                return this.mUIMainSecondaryPane1;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIMainSecondaryPane1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICustomerInfo__ctl4_mTable : HtmlTable
    {
        
        public UICustomerInfo__ctl4_mTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = "CustomerInfo__ctl4_mbodyTable";
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Quote Policy\r\n\r\nQuote Policy_URN101607\r\n";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "id=CustomerInfo__ctl4_mbodyTable height=\"100%\" cellSpacing=0 cellPadding=0 width=" +
                "\"100%\" border=0";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "2";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "1";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = null;
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "28";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public HtmlCell UIItemCell
        {
            get
            {
                if ((this.mUIItemCell == null))
                {
                    this.mUIItemCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = null;
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = null;
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "1";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "1006";
                    this.mUIItemCell.WindowTitles.Add("Customer View");
                    #endregion
                }
                return this.mUIItemCell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUIItemCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIEmailMessageInternetWindow : BrowserWindow
    {
        
        public UIEmailMessageInternetWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Email Message";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Email Message");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIEmailMessageDocument UIEmailMessageDocument
        {
            get
            {
                if ((this.mUIEmailMessageDocument == null))
                {
                    this.mUIEmailMessageDocument = new UIEmailMessageDocument(this);
                }
                return this.mUIEmailMessageDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIEmailMessageDocument mUIEmailMessageDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIEmailMessageDocument : HtmlDocument
    {
        
        public UIEmailMessageDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Email Message";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/MHCustomerView/WebPages/EmailMessage/EmailMessage.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://stt-pb-pdi-001.test.directpi.co.uk/MHCustomerView/WebPages/EmailMessage/Em" +
                "ailMessage.aspx?MessageId=839783";
            this.WindowTitles.Add("Email Message");
            #endregion
        }
        
        #region Properties
        public UI_ctl0_MessageContentFrame UI_ctl0_MessageContentFrame
        {
            get
            {
                if ((this.mUI_ctl0_MessageContentFrame == null))
                {
                    this.mUI_ctl0_MessageContentFrame = new UI_ctl0_MessageContentFrame(this);
                }
                return this.mUI_ctl0_MessageContentFrame;
            }
        }
        #endregion
        
        #region Fields
        private UI_ctl0_MessageContentFrame mUI_ctl0_MessageContentFrame;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UI_ctl0_MessageContentFrame : HtmlIFrame
    {
        
        public UI_ctl0_MessageContentFrame(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlFrame.PropertyNames.Id] = "_ctl0_MessageContentIFrame_directRef";
            this.SearchProperties[HtmlFrame.PropertyNames.Name] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.AbsolutePath] = "/MHCustomerView/WebPages/EmailMessage/EmailMessage.aspx";
            this.FilterProperties[HtmlFrame.PropertyNames.PageUrl] = "http://stt-pb-pdi-001.test.directpi.co.uk/MHCustomerView/WebPages/EmailMessage/Em" +
                "ailMessage.aspx?MessageId=839783&StreamContent=true";
            this.FilterProperties[HtmlFrame.PropertyNames.Title] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.Class] = "MessageContentIFrame";
            this.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "id=_ctl0_MessageContentIFrame_directRef ";
            this.FilterProperties[HtmlFrame.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("Email Message");
            #endregion
        }
        
        #region Properties
        public UINewsletterDocument UINewsletterDocument
        {
            get
            {
                if ((this.mUINewsletterDocument == null))
                {
                    this.mUINewsletterDocument = new UINewsletterDocument(this);
                }
                return this.mUINewsletterDocument;
            }
        }
        #endregion
        
        #region Fields
        private UINewsletterDocument mUINewsletterDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UINewsletterDocument : HtmlDocument
    {
        
        public UINewsletterDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Newsletter";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/MHCustomerView/WebPages/EmailMessage/EmailMessage.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://stt-pb-pdi-001.test.directpi.co.uk/MHCustomerView/WebPages/EmailMessage/Em" +
                "ailMessage.aspx?MessageId=839783&StreamContent=true";
            this.WindowTitles.Add("Email Message");
            #endregion
        }
        
        #region Properties
        public UIMainSection_item_0Table UIMainSection_item_0Table
        {
            get
            {
                if ((this.mUIMainSection_item_0Table == null))
                {
                    this.mUIMainSection_item_0Table = new UIMainSection_item_0Table(this);
                }
                return this.mUIMainSection_item_0Table;
            }
        }
        
        public HtmlSpan UICoveaInsuranceplcisrPane
        {
            get
            {
                if ((this.mUICoveaInsuranceplcisrPane == null))
                {
                    this.mUICoveaInsuranceplcisrPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUICoveaInsuranceplcisrPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUICoveaInsuranceplcisrPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUICoveaInsuranceplcisrPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Covea Insurance plc is registered in Eng";
                    this.mUICoveaInsuranceplcisrPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUICoveaInsuranceplcisrPane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUICoveaInsuranceplcisrPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "style=\"FONT-SIZE: 7.5pt; FONT-FAMILY: &amp;quot; PADDING-BOTTOM: 10px; PADDING-TO" +
                        "P: 10px; LINE-HEIGHT: 115%\"";
                    this.mUICoveaInsuranceplcisrPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "54";
                    this.mUICoveaInsuranceplcisrPane.WindowTitles.Add("Email Message");
                    #endregion
                }
                return this.mUICoveaInsuranceplcisrPane;
            }
        }
        #endregion
        
        #region Fields
        private UIMainSection_item_0Table mUIMainSection_item_0Table;
        
        private HtmlSpan mUICoveaInsuranceplcisrPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMainSection_item_0Table : HtmlTable
    {
        
        public UIMainSection_item_0Table(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = "MainSection_item_0";
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Hi Aaaaa,\r\n\r\nWe\'ve saved your quote with";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "id=MainSection_item_0 class=bodyTableCell style=\"MAX-WIDTH: 600px; HEIGHT: 100% !" +
                "important; WIDTH: 100% !important\" height=\"100%\" cellSpacing=0 cellPadding=0 wid" +
                "th=\"100%\" border=0";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "2";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "2";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "bodyTableCell";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "4";
            this.WindowTitles.Add("Email Message");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIHiAaaaaWevesavedyourPane
        {
            get
            {
                if ((this.mUIHiAaaaaWevesavedyourPane == null))
                {
                    this.mUIHiAaaaaWevesavedyourPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIHiAaaaaWevesavedyourPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIHiAaaaaWevesavedyourPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIHiAaaaaWevesavedyourPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Hi Aaaaa,\r\n\r\nWe\'ve saved your quote with";
                    this.mUIHiAaaaaWevesavedyourPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIHiAaaaaWevesavedyourPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "co_textnormal_Tahoma_Normal";
                    this.mUIHiAaaaaWevesavedyourPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=co_textnormal_Tahoma_Normal style=\"WORD-WRAP: break-word; FONT-SIZE: 11pt; " +
                        "FONT-FAMILY: tahoma; WIDTH: 580px; COLOR: #5a5e5e\"";
                    this.mUIHiAaaaaWevesavedyourPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "6";
                    this.mUIHiAaaaaWevesavedyourPane.WindowTitles.Add("Email Message");
                    #endregion
                }
                return this.mUIHiAaaaaWevesavedyourPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIHiAaaaaWevesavedyourPane;
        #endregion
    }
}
