// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Validate - Use 'ValidateParams' to pass parameters into this method.
        /// </summary>
        public void Validate()
        {
            #region Variable Declarations
            WinEdit uIAddressandsearchusinEdit = this.UICoveaHomeInternetExpWindow.UIAddressBarClient.UIAddressandsearchusinEdit;
            WinMenuItem uIPasteMenuItem = this.UIItemWindow.UIContextMenu.UIPasteMenuItem;
            BrowserWindow uICoveaHomeInternetExpWindow = this.UICoveaHomeInternetExpWindow;
            HtmlEdit uIIDEdit = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument.UIIDEdit;
            HtmlInputButton uISearchButton = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument.UISearchButton;
            HtmlInputButton uISearchButton1 = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument.UISearchButton1;
            HtmlCell uIItem924201814517PMCell = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument.UIDGTable.UIItem924201814517PMCell;
            HtmlCell uIItemCell = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument2.UIOne2many__ctl4_one2MTable.UIItemCell;
            HtmlSpan uIDialogsPane1 = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument2.UIDialogsPane.UIDialogsPane1;
            HtmlCell uIAaQP11SendQuoteConfiCell = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument2.UIOne2many__ctl4_ifrmOFrame.UIOne2ManyDocument.UI_ctl0_gridOne2ManyTable.UIAaQP11SendQuoteConfiCell;
            HtmlSpan uIMessagesPane = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument2.UIMessagesPane;
            HtmlSpan uIMessagesPane1 = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument2.UIMessagesPane.UIMessagesPane1;
            HtmlCell uIQP102QuoteConfirmatiCell = this.UICoveaHomeInternetExpWindow.UICustomerViewDocument2.UIOne2many__ctl4_ifrmOFrame1.UIOne2ManyDocument.UI_ctl0_gridOne2ManyTable.UIQP102QuoteConfirmatiCell;
            #endregion

            // Go to web page 'http://connect/' using new browser instance
            this.UICoveaHomeInternetExpWindow.LaunchUrl(new System.Uri(this.ValidateParams.UICoveaHomeInternetExpWindowUrl));

            // Click 'Address and search using Bing' text box
            Mouse.Click(uIAddressandsearchusinEdit, new Point(90, 4));

            // Right-Click 'Address and search using Bing' text box
            Mouse.Click(uIAddressandsearchusinEdit, MouseButtons.Right, ModifierKeys.None, new Point(90, 4));

            // Click 'Paste' menu item
            Mouse.Click(uIPasteMenuItem, new Point(52, 10));

            // Go to web page 'http://stt-pb-pdi-001.test.directpi.co.uk/MhCustomerView/WebPages/Search.aspx?DomainId=1025'
            uICoveaHomeInternetExpWindow.NavigateToUrl(new System.Uri(this.ValidateParams.UICoveaHomeInternetExpWindowUrl1));

            // Type 's3/18267/002BQ' in 'ID' text box
            uIIDEdit.Text = this.ValidateParams.UIIDEditText;

            // Click 'Search' button
            Mouse.Click(uISearchButton, new Point(28, 8));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'Search' button at (1, 1)
            Mouse.Hover(uISearchButton1, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Wait for 2 seconds for user delay between actions; Double-Click '9/24/2018 1:45:17 PM' cell
            Playback.Wait(2000);
            Mouse.DoubleClick(uIItem924201814517PMCell, new Point(97, 11));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover  cell at (1, 1)
            Mouse.Hover(uIItemCell, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Dialogs' pane
            Mouse.Click(uIDialogsPane1, new Point(17, 10));

            // Click 'Aa- QP 11 - Send Quote Confirmation - Ch' cell
            Mouse.Click(uIAaQP11SendQuoteConfiCell, new Point(191, 10));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'Messages' pane at (1, 1)
            Mouse.Hover(uIMessagesPane, new Point(1, 1));

            // Mouse hover 'Messages' pane at (1, 1)
            Mouse.Hover(uIMessagesPane1, new Point(1, 1));

            // Mouse hover  cell at (1, 1)
            Mouse.Hover(uIItemCell, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Messages' pane
            Mouse.Click(uIMessagesPane1, new Point(30, 13));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'Messages' pane at (1, 1)
            Mouse.Hover(uIMessagesPane, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'QP - 102 Quote Confirmation' cell
            Mouse.Click(uIQP102QuoteConfirmatiCell, new Point(119, 10));
        }
        
        #region Properties
        public virtual ValidateParams ValidateParams
        {
            get
            {
                if ((this.mValidateParams == null))
                {
                    this.mValidateParams = new ValidateParams();
                }
                return this.mValidateParams;
            }
        }
        
        public UICoveaHomeInternetExpWindow UICoveaHomeInternetExpWindow
        {
            get
            {
                if ((this.mUICoveaHomeInternetExpWindow == null))
                {
                    this.mUICoveaHomeInternetExpWindow = new UICoveaHomeInternetExpWindow();
                }
                return this.mUICoveaHomeInternetExpWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private ValidateParams mValidateParams;
        
        private UICoveaHomeInternetExpWindow mUICoveaHomeInternetExpWindow;
        
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Validate'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class ValidateParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://connect/' using new browser instance
        /// </summary>
        public string UICoveaHomeInternetExpWindowUrl = "http://connect/";
        
        /// <summary>
        /// Go to web page 'http://stt-pb-pdi-001.test.directpi.co.uk/MhCustomerView/WebPages/Search.aspx?DomainId=1025'
        /// </summary>
        public string UICoveaHomeInternetExpWindowUrl1 = "http://stt-pb-pdi-001.test.directpi.co.uk/MhCustomerView/WebPages/Search.aspx?Dom" +
            "ainId=1025";
        
        /// <summary>
        /// Type 's3/18267/002BQ' in 'ID' text box
        /// </summary>
        public string UIIDEditText = "s3/18267/002BQ";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICoveaHomeInternetExpWindow : BrowserWindow
    {
        
        public UICoveaHomeInternetExpWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "CoveaHome";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("CoveaHome");
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIAddressBarClient UIAddressBarClient
        {
            get
            {
                if ((this.mUIAddressBarClient == null))
                {
                    this.mUIAddressBarClient = new UIAddressBarClient(this);
                }
                return this.mUIAddressBarClient;
            }
        }
        
        public UICustomerViewDocument UICustomerViewDocument
        {
            get
            {
                if ((this.mUICustomerViewDocument == null))
                {
                    this.mUICustomerViewDocument = new UICustomerViewDocument(this);
                }
                return this.mUICustomerViewDocument;
            }
        }
        
        public UICustomerViewDocument2 UICustomerViewDocument2
        {
            get
            {
                if ((this.mUICustomerViewDocument2 == null))
                {
                    this.mUICustomerViewDocument2 = new UICustomerViewDocument2(this);
                }
                return this.mUICustomerViewDocument2;
            }
        }
        #endregion
        
        #region Fields
        private UIAddressBarClient mUIAddressBarClient;
        
        private UICustomerViewDocument mUICustomerViewDocument;
        
        private UICustomerViewDocument2 mUICustomerViewDocument2;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIAddressBarClient : WinClient
    {
        
        public UIAddressBarClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Address Bar";
            this.WindowTitles.Add("CoveaHome");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAddressandsearchusinEdit
        {
            get
            {
                if ((this.mUIAddressandsearchusinEdit == null))
                {
                    this.mUIAddressandsearchusinEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAddressandsearchusinEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Address and search using Bing";
                    this.mUIAddressandsearchusinEdit.WindowTitles.Add("CoveaHome");
                    #endregion
                }
                return this.mUIAddressandsearchusinEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAddressandsearchusinEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICustomerViewDocument : HtmlDocument
    {
        
        public UICustomerViewDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "Body";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Customer View";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/MhCustomerView/WebPages/Search.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://stt-pb-pdi-001.test.directpi.co.uk/MhCustomerView/WebPages/Search.aspx?Dom" +
                "ainId=1025";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIIDEdit
        {
            get
            {
                if ((this.mUIIDEdit == null))
                {
                    this.mUIIDEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIIDEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "SearchPanel_Normal_QuotePolicy__QE_ID";
                    this.mUIIDEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "SearchPanel:Normal:QuotePolicy__QE_ID";
                    this.mUIIDEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIIDEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIIDEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIIDEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "input";
                    this.mUIIDEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "onfocus=\"javascript: document.getElement";
                    this.mUIIDEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "15";
                    this.mUIIDEdit.WindowTitles.Add("Customer View");
                    #endregion
                }
                return this.mUIIDEdit;
            }
        }
        
        public HtmlInputButton UISearchButton
        {
            get
            {
                if ((this.mUISearchButton == null))
                {
                    this.mUISearchButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUISearchButton.SearchProperties[HtmlButton.PropertyNames.Id] = "SearchPanel_Normal_SearchButton";
                    this.mUISearchButton.SearchProperties[HtmlButton.PropertyNames.Name] = "SearchPanel:Normal:SearchButton";
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = "Search";
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.Title] = "Start search";
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.Class] = "Button";
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "onclick=\"var flag=true;if (typeof(Page_C";
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "509";
                    this.mUISearchButton.WindowTitles.Add("Customer View");
                    #endregion
                }
                return this.mUISearchButton;
            }
        }
        
        public HtmlInputButton UISearchButton1
        {
            get
            {
                if ((this.mUISearchButton1 == null))
                {
                    this.mUISearchButton1 = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUISearchButton1.SearchProperties[HtmlButton.PropertyNames.Id] = "SearchPanel_Normal_SearchButton";
                    this.mUISearchButton1.SearchProperties[HtmlButton.PropertyNames.Name] = "SearchPanel:Normal:SearchButton";
                    this.mUISearchButton1.FilterProperties[HtmlButton.PropertyNames.DisplayText] = "Search";
                    this.mUISearchButton1.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISearchButton1.FilterProperties[HtmlButton.PropertyNames.Title] = "Start search";
                    this.mUISearchButton1.FilterProperties[HtmlButton.PropertyNames.Class] = "ButtonOver";
                    this.mUISearchButton1.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "onclick=\"var flag=true;if (typeof(Page_C";
                    this.mUISearchButton1.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "509";
                    this.mUISearchButton1.WindowTitles.Add("Customer View");
                    #endregion
                }
                return this.mUISearchButton1;
            }
        }
        
        public UIDGTable UIDGTable
        {
            get
            {
                if ((this.mUIDGTable == null))
                {
                    this.mUIDGTable = new UIDGTable(this);
                }
                return this.mUIDGTable;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIIDEdit;
        
        private HtmlInputButton mUISearchButton;
        
        private HtmlInputButton mUISearchButton1;
        
        private UIDGTable mUIDGTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDGTable : HtmlTable
    {
        
        public UIDGTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = "Dg";
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "mh_customer_idmh_contextmh_participant_i";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "id=Dg class=grid onselectstart=\"return false\" style=\"WIDTH: 100%; BORDER-COLLAPSE" +
                ": collapse\" cellSpacing=0 rules=all border=1";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "2";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "97";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "grid";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "567";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public HtmlCell UIItem924201814517PMCell
        {
            get
            {
                if ((this.mUIItem924201814517PMCell == null))
                {
                    this.mUIItem924201814517PMCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIItem924201814517PMCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIItem924201814517PMCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIItem924201814517PMCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIItem924201814517PMCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "9/24/2018 1:45:17 PM";
                    this.mUIItem924201814517PMCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "noWrap";
                    this.mUIItem924201814517PMCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "1";
                    this.mUIItem924201814517PMCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "6";
                    this.mUIItem924201814517PMCell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUIItem924201814517PMCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "1296";
                    this.mUIItem924201814517PMCell.WindowTitles.Add("Customer View");
                    #endregion
                }
                return this.mUIItem924201814517PMCell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUIItem924201814517PMCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICustomerViewDocument2 : HtmlDocument
    {
        
        public UICustomerViewDocument2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "Body";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Customer View";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/MhCustomerView/WebPages/Customer.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://stt-pb-pdi-001.test.directpi.co.uk/MhCustomerView/WebPages/Customer.aspx?D" +
                "omainId=1025&CustomerId=101599";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public UIOne2many__ctl4_one2MTable UIOne2many__ctl4_one2MTable
        {
            get
            {
                if ((this.mUIOne2many__ctl4_one2MTable == null))
                {
                    this.mUIOne2many__ctl4_one2MTable = new UIOne2many__ctl4_one2MTable(this);
                }
                return this.mUIOne2many__ctl4_one2MTable;
            }
        }
        
        public UIDialogsPane UIDialogsPane
        {
            get
            {
                if ((this.mUIDialogsPane == null))
                {
                    this.mUIDialogsPane = new UIDialogsPane(this);
                }
                return this.mUIDialogsPane;
            }
        }
        
        public UIOne2many__ctl4_ifrmOFrame UIOne2many__ctl4_ifrmOFrame
        {
            get
            {
                if ((this.mUIOne2many__ctl4_ifrmOFrame == null))
                {
                    this.mUIOne2many__ctl4_ifrmOFrame = new UIOne2many__ctl4_ifrmOFrame(this);
                }
                return this.mUIOne2many__ctl4_ifrmOFrame;
            }
        }
        
        public UIMessagesPane UIMessagesPane
        {
            get
            {
                if ((this.mUIMessagesPane == null))
                {
                    this.mUIMessagesPane = new UIMessagesPane(this);
                }
                return this.mUIMessagesPane;
            }
        }
        
        public UIOne2many__ctl4_ifrmOFrame1 UIOne2many__ctl4_ifrmOFrame1
        {
            get
            {
                if ((this.mUIOne2many__ctl4_ifrmOFrame1 == null))
                {
                    this.mUIOne2many__ctl4_ifrmOFrame1 = new UIOne2many__ctl4_ifrmOFrame1(this);
                }
                return this.mUIOne2many__ctl4_ifrmOFrame1;
            }
        }
        #endregion
        
        #region Fields
        private UIOne2many__ctl4_one2MTable mUIOne2many__ctl4_one2MTable;
        
        private UIDialogsPane mUIDialogsPane;
        
        private UIOne2many__ctl4_ifrmOFrame mUIOne2many__ctl4_ifrmOFrame;
        
        private UIMessagesPane mUIMessagesPane;
        
        private UIOne2many__ctl4_ifrmOFrame1 mUIOne2many__ctl4_ifrmOFrame1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIOne2many__ctl4_one2MTable : HtmlTable
    {
        
        public UIOne2many__ctl4_one2MTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = "one2many__ctl4_one2ManyTable";
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Drivers\r\nClaims\r\nClaims_Customer Level\r\n";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "id=one2many__ctl4_one2ManyTable style=\"HEIGHT: 100%; WIDTH: 100%\" cellSpacing=0 c" +
                "ellPadding=0";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "4";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "1";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = null;
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "356";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public HtmlCell UIItemCell
        {
            get
            {
                if ((this.mUIItemCell == null))
                {
                    this.mUIItemCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = null;
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = null;
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "2";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "1077";
                    this.mUIItemCell.WindowTitles.Add("Customer View");
                    #endregion
                }
                return this.mUIItemCell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUIItemCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDialogsPane : HtmlSpan
    {
        
        public UIDialogsPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "one2many__ctl4_tabStrip_tab_10";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Dialogs";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "TabItem";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = @"onclick=""javascript: one2many__ctl4_tabStrip_Click(one2many__ctl4_tabStrip_tab_10,'one2many__ctl4_TabStrip_',10,14,'TabItem','TabItemSelected');"" onmouseover=""javascript: this.style.cursor = 'hand'"" id=one2many__ctl4_tabStrip_tab_10 class=TabItem style=""HEIGHT: 21px; DISPLAY: inline-block""";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "654";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public HtmlSpan UIDialogsPane1
        {
            get
            {
                if ((this.mUIDialogsPane1 == null))
                {
                    this.mUIDialogsPane1 = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIDialogsPane1.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIDialogsPane1.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIDialogsPane1.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Dialogs";
                    this.mUIDialogsPane1.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIDialogsPane1.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIDialogsPane1.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = null;
                    this.mUIDialogsPane1.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "655";
                    this.mUIDialogsPane1.WindowTitles.Add("Customer View");
                    #endregion
                }
                return this.mUIDialogsPane1;
            }
        }
        #endregion
        
        #region Fields
        private HtmlSpan mUIDialogsPane1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIOne2many__ctl4_ifrmOFrame : HtmlIFrame
    {
        
        public UIOne2many__ctl4_ifrmOFrame(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlFrame.PropertyNames.Id] = "one2many__ctl4_ifrmOne2Many10";
            this.SearchProperties[HtmlFrame.PropertyNames.Name] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.AbsolutePath] = "/MHCustomerView/WebPages/One2ManyGroup.aspx";
            this.FilterProperties[HtmlFrame.PropertyNames.PageUrl] = "/MHCustomerView/WebPages/One2ManyGroup.aspx?DGN=Dialogs&CustomerId=101599&CustDom" +
                "ainId=1025";
            this.FilterProperties[HtmlFrame.PropertyNames.Title] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.Class] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "id=one2many__ctl4_ifrmOne2Many10 style=\"";
            this.FilterProperties[HtmlFrame.PropertyNames.TagInstance] = "11";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public UIOne2ManyDocument UIOne2ManyDocument
        {
            get
            {
                if ((this.mUIOne2ManyDocument == null))
                {
                    this.mUIOne2ManyDocument = new UIOne2ManyDocument(this);
                }
                return this.mUIOne2ManyDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIOne2ManyDocument mUIOne2ManyDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIOne2ManyDocument : HtmlDocument
    {
        
        public UIOne2ManyDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "One2Many";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/MHCustomerView/WebPages/One2ManyGroup.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://stt-pb-pdi-001.test.directpi.co.uk/MHCustomerView/WebPages/One2ManyGroup.a" +
                "spx?DGN=Dialogs&CustomerId=101599&CustDomainId=1025";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public UI_ctl0_gridOne2ManyTable UI_ctl0_gridOne2ManyTable
        {
            get
            {
                if ((this.mUI_ctl0_gridOne2ManyTable == null))
                {
                    this.mUI_ctl0_gridOne2ManyTable = new UI_ctl0_gridOne2ManyTable(this);
                }
                return this.mUI_ctl0_gridOne2ManyTable;
            }
        }
        #endregion
        
        #region Fields
        private UI_ctl0_gridOne2ManyTable mUI_ctl0_gridOne2ManyTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UI_ctl0_gridOne2ManyTable : HtmlTable
    {
        
        public UI_ctl0_gridOne2ManyTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = "_ctl0_gridOne2Many";
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "dp_idDialog NameGroup NameContextEntered";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "id=_ctl0_gridOne2Many style=\"WIDTH: 100%; BORDER-COLLAPSE: collapse\" cellSpacing=" +
                "0 rules=all border=1";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "2";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "6";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = null;
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "2";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public HtmlCell UIAaQP11SendQuoteConfiCell
        {
            get
            {
                if ((this.mUIAaQP11SendQuoteConfiCell == null))
                {
                    this.mUIAaQP11SendQuoteConfiCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIAaQP11SendQuoteConfiCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIAaQP11SendQuoteConfiCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIAaQP11SendQuoteConfiCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIAaQP11SendQuoteConfiCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "Aa- QP 11 - Send Quote Confirmation - Ch";
                    this.mUIAaQP11SendQuoteConfiCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "noWrap Unselectable=\"On\"";
                    this.mUIAaQP11SendQuoteConfiCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "1";
                    this.mUIAaQP11SendQuoteConfiCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "1";
                    this.mUIAaQP11SendQuoteConfiCell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUIAaQP11SendQuoteConfiCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "9";
                    this.mUIAaQP11SendQuoteConfiCell.WindowTitles.Add("Customer View");
                    #endregion
                }
                return this.mUIAaQP11SendQuoteConfiCell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUIAaQP11SendQuoteConfiCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMessagesPane : HtmlSpan
    {
        
        public UIMessagesPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "one2many__ctl4_tabStrip_tab_9";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Messages";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "TabItem";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = @"onclick=""javascript: one2many__ctl4_tabStrip_Click(one2many__ctl4_tabStrip_tab_9,'one2many__ctl4_TabStrip_',9,14,'TabItem','TabItemSelected');"" onmouseover=""javascript: this.style.cursor = 'hand'"" id=one2many__ctl4_tabStrip_tab_9 class=TabItem style=""HEIGHT: 21px; DISPLAY: inline-block""";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "652";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public HtmlSpan UIMessagesPane1
        {
            get
            {
                if ((this.mUIMessagesPane1 == null))
                {
                    this.mUIMessagesPane1 = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIMessagesPane1.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIMessagesPane1.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIMessagesPane1.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Messages";
                    this.mUIMessagesPane1.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIMessagesPane1.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIMessagesPane1.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = null;
                    this.mUIMessagesPane1.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "653";
                    this.mUIMessagesPane1.WindowTitles.Add("Customer View");
                    #endregion
                }
                return this.mUIMessagesPane1;
            }
        }
        #endregion
        
        #region Fields
        private HtmlSpan mUIMessagesPane1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIOne2many__ctl4_ifrmOFrame1 : HtmlIFrame
    {
        
        public UIOne2many__ctl4_ifrmOFrame1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlFrame.PropertyNames.Id] = "one2many__ctl4_ifrmOne2Many9";
            this.SearchProperties[HtmlFrame.PropertyNames.Name] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.AbsolutePath] = "/MHCustomerView/WebPages/One2ManyGroup.aspx";
            this.FilterProperties[HtmlFrame.PropertyNames.PageUrl] = "/MHCustomerView/WebPages/One2ManyGroup.aspx?DGN=Messages&CustomerId=101599&CustDo" +
                "mainId=1025";
            this.FilterProperties[HtmlFrame.PropertyNames.Title] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.Class] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "id=one2many__ctl4_ifrmOne2Many9 style=\"H";
            this.FilterProperties[HtmlFrame.PropertyNames.TagInstance] = "10";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public UIOne2ManyDocument1 UIOne2ManyDocument
        {
            get
            {
                if ((this.mUIOne2ManyDocument == null))
                {
                    this.mUIOne2ManyDocument = new UIOne2ManyDocument1(this);
                }
                return this.mUIOne2ManyDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIOne2ManyDocument1 mUIOne2ManyDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIOne2ManyDocument1 : HtmlDocument
    {
        
        public UIOne2ManyDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "One2Many";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/MHCustomerView/WebPages/One2ManyGroup.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://stt-pb-pdi-001.test.directpi.co.uk/MHCustomerView/WebPages/One2ManyGroup.a" +
                "spx?DGN=Messages&CustomerId=101599&CustDomainId=1025";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public UI_ctl0_gridOne2ManyTable1 UI_ctl0_gridOne2ManyTable
        {
            get
            {
                if ((this.mUI_ctl0_gridOne2ManyTable == null))
                {
                    this.mUI_ctl0_gridOne2ManyTable = new UI_ctl0_gridOne2ManyTable1(this);
                }
                return this.mUI_ctl0_gridOne2ManyTable;
            }
        }
        #endregion
        
        #region Fields
        private UI_ctl0_gridOne2ManyTable1 mUI_ctl0_gridOne2ManyTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UI_ctl0_gridOne2ManyTable1 : HtmlTable
    {
        
        public UI_ctl0_gridOne2ManyTable1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = "_ctl0_gridOne2Many";
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "ml_idcm_idMessage NameTypeContextCreated";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "id=_ctl0_gridOne2Many style=\"WIDTH: 100%; BORDER-COLLAPSE: collapse\" cellSpacing=" +
                "0 rules=all border=1";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "2";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "11";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = null;
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "2";
            this.WindowTitles.Add("Customer View");
            #endregion
        }
        
        #region Properties
        public HtmlCell UIQP102QuoteConfirmatiCell
        {
            get
            {
                if ((this.mUIQP102QuoteConfirmatiCell == null))
                {
                    this.mUIQP102QuoteConfirmatiCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIQP102QuoteConfirmatiCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIQP102QuoteConfirmatiCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIQP102QuoteConfirmatiCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIQP102QuoteConfirmatiCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "QP - 102 Quote Confirmation";
                    this.mUIQP102QuoteConfirmatiCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "noWrap Unselectable=\"On\"";
                    this.mUIQP102QuoteConfirmatiCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "1";
                    this.mUIQP102QuoteConfirmatiCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "2";
                    this.mUIQP102QuoteConfirmatiCell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUIQP102QuoteConfirmatiCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "15";
                    this.mUIQP102QuoteConfirmatiCell.WindowTitles.Add("Customer View");
                    #endregion
                }
                return this.mUIQP102QuoteConfirmatiCell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUIQP102QuoteConfirmatiCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Context";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32768";
            #endregion
        }
        
        #region Properties
        public UIContextMenu UIContextMenu
        {
            get
            {
                if ((this.mUIContextMenu == null))
                {
                    this.mUIContextMenu = new UIContextMenu(this);
                }
                return this.mUIContextMenu;
            }
        }
        #endregion
        
        #region Fields
        private UIContextMenu mUIContextMenu;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIContextMenu : WinMenu
    {
        
        public UIContextMenu(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenu.PropertyNames.Name] = "Context";
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIPasteMenuItem
        {
            get
            {
                if ((this.mUIPasteMenuItem == null))
                {
                    this.mUIPasteMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIPasteMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Paste";
                    #endregion
                }
                return this.mUIPasteMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIPasteMenuItem;
        #endregion
    }
}
